### PR TITLE
set the default axis image directory to the default image directory

### PR DESCRIPTION
**Pull request by dbox**
This will just allow axis image mixins to work right away without paths.

### CODE REVIEW

**Comment by jenius** [comment]
I feel like I'd rather use an absolute path here, just because nested html files etc.

**Comment by dbox** [comment]
how do you mean?

**Comment by jenius** [comment]
`"/img/"`

**Comment by dbox** [comment]
Crazy. I didn't even think that would work. I thought you had to go back a directory, then into `images`, but just tested and totally works. 

You agree that the default should be set though, yes?

**Comment by jenius** [comment]
yeah definitely agreed. why not, its an absolute path!

**Comment by dbox** [comment]
fixed

**Comment by jenius** [comment]
Perfect. Thank ya!

**Pull request merged**
