### PR TITLE
Upgrade axis

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
The coninuation from https://github.com/roots-dev/base/issues/12 Upgrades Axis, and the variables used by it in _settings.styl.

### CODE REVIEW

**Comment by SevereOverfl0w** [comment]
Just tested this locally, worked well for me.

**Comment by dbox** [comment]
nice. Just for future refernece axis docs are here: http://axis.netlify.com

**Comment by dbox** [comment]
Might as well upgrade autoprefixer now too:

https://github.com/jenius/autoprefixer-stylus/releases/tag/v0.8.0

**Comment by SevereOverfl0w** [comment]
RE doc location, yep, but they appear slightly dated, and lack a mention of the settings.

I wish there was an easy way to use npm upgrade on the template directly. I'll run the template locally, and see what needs updating.

**Comment by dbox** [comment]
I think @jenius was trying out some new service that automagically keeps dependencies up to date too. Might be good to add to this repo as well.

**Comment by dbox** [comment]
Yeah, you actually don't even need the settings, only if you want to overwrite stuff, but we need to get some sort of writeup about that in the docs. Everything else SHOULD be pretty up to date though.

**Comment by SevereOverfl0w** [comment]
Would that work here, as the package.json isn't yet generated?

**Comment by dbox** [comment]
Don't know

**Comment by SevereOverfl0w** [comment]
coffee-script and autoprefixer-stylus look good, no api changes. jstransformer-marked 0.0.2 -> 1.0.1 had no actual changes, was just marked as stable. Can't see any stylus api changes either.

Should everything that's stable by semantic versioning standards be put down as ^1.0.0, so that it's always using the latest major version of the library? Seems to make most sense to me.

**Comment by dbox** [comment]
why would we not want most up to date autoprefixer?

**Comment by SevereOverfl0w** [comment]
Semantic versioning dictates that the api between minor versions when the major is 0 (e.g. 0.7.0 to 0.8.0) cannot be considered stable.

**Comment by dbox** [comment]
@jenius Does things a little bit differently. Read more here:

http://markup.im/#q4_cRZ1Q

**Comment by SevereOverfl0w** [comment]
From that document:
> Once the minor version is above zero, the patch version will be bumped for patches and bug fixes, and the minor version will be bumped for breaking changes. So it would be a good idea to lock the package at 0.1.x, replacing 1 with whatever the minor version is on when you start using the library.

**Comment by dbox** [comment]
yeah, in this versioning the 2nd number can container breaking changes and be considered more "major" than normal semver, from what I understand. but he can speak more to it.

**Comment by jenius** [comment]
Ah yes, for the base template we can make "breaking" updates. This template is just used once when generating new projects, so it's ok for us to upgrade it as needed. If you are concerned about breaking changes, just git tag releases, and people can grab an older version if they need ([docs](https://github.com/carrot/sprout#versioning-templates))

**Comment by jenius** [comment]
And I do things exactly according to the semver spec, as you cited @SevereOverfl0w :grinning:

**Comment by dbox** [comment]
So we should update autoprefixer in this case right?

**Comment by jenius** [comment]
Yes

**Comment by SevereOverfl0w** [comment]
I thought that was normal semver, it's what I thought it was... 

Either way, we agree that we wouldn't want to auto-install autoprefixer-stylus to 0.9.0 or even 1.0.0, without having tested it first. Which means where $MAJOR < 1, we should try and fix on Minor.

Yes @dbox. I think you may have misread what I said, I said we should update it! I don't think I worded that comment well. I meant that there were no API changes in either of those libs, so updating was no problem.

**Comment by dbox** [comment]
Haha. sorry! i don't sleep much!

**Comment by jenius** [comment]
So yeah I'm going to merge this, then we can open another PR to bring all the other dependencies up to date. If that's cool.

**Comment by SevereOverfl0w** [comment]
Oops. I'll try remove that last commit.

**Comment by jenius** [comment]
Hah no it's fine!

**Comment by jenius** [comment]
Thanks for the updates here :+1: :tada:

**Comment by dbox** [comment]
@jenius already read it. Great stuff, but I'm looking for the update after you've had a kid, or 4 :)

**Comment by SevereOverfl0w** [comment]
@jenius just to confirm, will sprout pull the latest version of base, and use that as the default template from now?

**Comment by jenius** [comment]
@SevereOverfl0w Yes it will!
@dbox fair enough. that makes it harder im sure, but i'll never give up my sleep! a plan will be hatched :grin:

**Comment by dbox** [comment]
👊🏻😴

**Pull request merged**
